# Generated by Django 4.2.25 on 2025-11-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uranai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daikichi', models.IntegerField(blank=True, default=0, null=True, verbose_name='大吉回数')),
                ('chukichi', models.IntegerField(blank=True, default=0, null=True, verbose_name='中吉回数')),
                ('shokichi', models.IntegerField(blank=True, default=0, null=True, verbose_name='小吉回数')),
                ('sum', models.IntegerField(blank=True, default=0, null=True, verbose_name='回数')),
            ],
        ),
    ]
