# Generated by Django 4.2.25 on 2025-11-11 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fortune', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uranai',
            name='sum',
        ),
        migrations.AddField(
            model_name='uranai',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日付'),
        ),
    ]
